### ISSUE TITLE
try_url.js : Not identified hash | update-todo: File not found

### ISSUE THREAD

**Issue by PureFallen** [sudofox/mojang-blocklist#2]
Following your advice in the last Pull Request #1, i have been trying to go through to routine of modifying the files in `data` by running `try_url.js`, `update-blocklist`, `update-merged` and `update-todo`.

`try_url.js` could not identify the IP-address as a hash in `todo.txt`, despite me knowing that this IP address was in fact recently blocked by Mojang.
Upon entering the find manually to `identified.txt`, i was able to run `update-blocklist` and `update-merged`, but would receive a `File Not Found`-Error with `update-todo`.

Node Version is `18.12.0`, npm Version is `8.19.3`.
The `sha1` dependency was installed using `npm install` of the `package.json`.
I used a fork equal to this repositories `master` branch in preparation for a later pull request.

Due to my inexperience with NodeJS i could imagine that this may be an issue error in my end, but in that case i am not really sure where i did something wrong.

![image](https://user-images.githubusercontent.com/68307987/200116939-6e3c643b-119b-4a8e-a17e-a09897f00c99.png)

**Comment by sudofox** [comment]
I'm not entirely sure. My initial thought is that maybe you didn't have the latest changes pulled down; though I don't think I've ever tested the repo on Windows. I checked your fork and it doesn't seem to be running the GitHub actions that I had set up, so it's possible you might not have had the latest changes.

I tried with that IP:

```
[aburk@aburk-laptop mojang-blocklist]$ node try_url.js 82.124.146.214
Identified de2bf9e82662dfbbc0983dee12a8a6a1cc646d6a as 82.124.146.214
de2bf9e82662dfbbc0983dee12a8a6a1cc646d6a=82.124.146.214
[aburk@aburk-laptop mojang-blocklist]$ npm run update-blocklist ; npm run update-merged; npm run update-todo ; git status data/

> mojang-blocklist@1.0.0 update-blocklist /home/aburk/git/mojang-blocklist
> node update_blocklist.js

Writing 2292 hashes (old count: 2292)

> mojang-blocklist@1.0.0 update-merged /home/aburk/git/mojang-blocklist
> node update_merged.js

wrote 2292 lines to data/merged.txt

> mojang-blocklist@1.0.0 update-todo /home/aburk/git/mojang-blocklist
> comm -23 <(sort -u data/current.txt) <(awk -F= '{print $1}' data/identified.txt |sort -u) | sort -u > data/todo.txt

<snip npm telling me its outdated and stuff>

On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   data/identified.txt
	modified:   data/merged.txt
	modified:   data/todo.txt
```

So it worked fine for me.

I don't have a Windows box handy to check from right now, and I'm away from home...not sure!

One note: if you already ID'd a string then `try_url.js` won't print it out a second time if you already have it in your files

**Comment by PureFallen** [comment]
Looking at the error thrown by `update-todo` i could imagine that it may interpreted one or another command as an actual file. So it could be related to Windows with the code only working on Linux.
When i happen to identify a new domain or ip, i will probably give it a shot.

**Comment by sudofox** [comment]
sound good to me, i'll close this and keep it in mind in the future. thanks!

**Comment by PureFallen** [comment]
I was able to produce a different error with `update-todo` on `Raspbian 10` with the recent Node and NPM versions.
`try_url.js` works now, `update-todo` throws an Syntax Error.

This makes me wonder if there could be distro-specific issues with the command, or if the problem is caused by newer Node/NPM versions.

```
> mojang-blocklist@1.0.0 update-todo
> comm -23 <(sort -u data/current.txt) <(awk -F= '{print $1}' data/identified.txt |sort -u) | sort -u > data/todo.txt

sh: 1: Syntax error: "(" unexpected
```
